-- Seed data for local development.
-- This runs automatically after `supabase db reset`.
-- The e2e test user is created at test time by web/e2e/global-setup.ts via the
-- Supabase admin API, not here, so it stays in sync with the auth schema.
