//! PostgreSQL DDL (every designer operation runs in place, in one
//! transaction) and the `RecordStore` impl for `PostgresRecordStore`.
use super::{apply_op, delete_on, insert_on, load_def, pe, update_on, PostgresRecordStore};
use crate::data::{
    q, AlterTable, ColumnDef, CreateTable, DataValue, IndexDef, LogicalType, NamedValue, TableDef,
};
use crate::recordstore::{
    capabilities, plan, ChangeMode, ChangePlan, CreateIndex, InboundForeignKey, RecordStore,
    ScriptReport, StoreCapabilities, StoreError, TableImpact, WriteOp, WriteOutcome,
};
use postgres::types::{ToSql, Type};

fn pg_type(c: &ColumnDef) -> String {
    c.logical_type.postgres_type()
}
fn column_sql(c: &ColumnDef, identity: bool) -> String {
    let mut out = format!("{} {}", q(&c.name), pg_type(c));
    if identity {
        out.push_str(" GENERATED BY DEFAULT AS IDENTITY");
    }
    if !c.nullable {
        out.push_str(" NOT NULL");
    }
    if let Some(d) = &c.default_expression {
        out.push_str(&format!(" DEFAULT {d}"));
    }
    if let Some(g) = &c.generated_expression {
        out.push_str(&format!(" GENERATED ALWAYS AS ({g}) STORED"));
    }
    out
}
fn cols(list: &[String]) -> String {
    list.iter().map(|c| q(c)).collect::<Vec<_>>().join(",")
}
/// PostgreSQL truncates identifiers to 63 bytes (NAMEDATALEN - 1).
const PG_IDENT_MAX: usize = 63;

/// A deterministic check constraint name, `<table>_<column>_check` like PostgreSQL's
/// own default, kept within 63 bytes (long names keep a prefix plus a hash) and made
/// unique against `taken` with a numeric suffix.
fn check_name(table: &str, column: Option<&str>, taken: &[&str]) -> String {
    let base = match column {
        Some(c) => format!("{table}_{c}_check"),
        None => format!("{table}_check"),
    };
    let fit = |s: String| -> String {
        if s.len() <= PG_IDENT_MAX {
            return s;
        }
        let hash = s.bytes().fold(0xcbf29ce484222325u64, |h, b| {
            (h ^ b as u64).wrapping_mul(0x100000001b3)
        });
        let mut cut = PG_IDENT_MAX - 17;
        while !s.is_char_boundary(cut) {
            cut -= 1;
        }
        format!("{}_{hash:016x}", &s[..cut])
    };
    let mut n = 0;
    loop {
        let candidate = fit(if n == 0 {
            base.clone()
        } else {
            format!("{base}{n}")
        });
        if !taken.iter().any(|t| t.eq_ignore_ascii_case(&candidate)) {
            return candidate;
        }
        n += 1;
    }
}

/// Names the checks `op` added to `after` (the plan leaves them unnamed) so a later
/// operation in the same batch can drop them by name.
fn name_new_checks(op: &AlterTable, table: &str, before: &TableDef, after: &mut TableDef) {
    let column = match op {
        AlterTable::AlterColumn { column, .. } => Some(column.as_str()),
        AlterTable::AddColumn { column } => Some(column.name.as_str()),
        _ => None,
    };
    for i in 0..after.checks.len() {
        if after.checks[i].name.is_some() || before.checks.contains(&after.checks[i]) {
            continue;
        }
        let taken: Vec<String> = before
            .checks
            .iter()
            .chain(after.checks.iter())
            .filter_map(|c| c.name.clone())
            .collect();
        let taken: Vec<&str> = taken.iter().map(String::as_str).collect();
        after.checks[i].name = Some(check_name(table, column, &taken));
    }
}

fn named(name: &Option<String>) -> String {
    name.as_deref()
        .map(|n| format!("CONSTRAINT {} ", q(n)))
        .unwrap_or_default()
}
fn fk_sql(f: &crate::data::ForeignKeyDef) -> String {
    format!(
        "{}FOREIGN KEY ({}) REFERENCES {} ({}) ON UPDATE {} ON DELETE {}",
        named(&f.name),
        cols(&f.columns),
        q(&f.target_table),
        cols(&f.target_columns),
        f.on_update,
        f.on_delete
    )
}
pub fn create_table_sql(def: &TableDef) -> Vec<String> {
    let identity_col = (def.primary_key.len() == 1)
        .then(|| def.column(&def.primary_key[0]))
        .flatten()
        .filter(|c| {
            c.logical_type == LogicalType::Integer
                && c.default_expression.is_none()
                && c.generated_expression.is_none()
        })
        .map(|c| c.name.clone());
    let mut parts: Vec<String> = def
        .columns
        .iter()
        .map(|c| column_sql(c, identity_col.as_deref() == Some(c.name.as_str())))
        .collect();
    if !def.primary_key.is_empty() {
        parts.push(format!(
            "{}PRIMARY KEY ({})",
            named(&def.primary_key_name),
            cols(&def.primary_key)
        ));
    }
    parts.extend(
        def.uniques
            .iter()
            .map(|u| format!("{}UNIQUE ({})", named(&u.name), cols(&u.columns))),
    );
    parts.extend(
        def.checks
            .iter()
            .map(|c| format!("{}CHECK ({})", named(&c.name), c.expression)),
    );
    parts.extend(def.foreign_keys.iter().map(fk_sql));
    let mut out = vec![format!(
        "CREATE TABLE {} ({})",
        q(&def.name),
        parts.join(", ")
    )];
    out.extend(def.indexes.iter().map(|i| index_sql(i, &def.name)));
    out
}
fn index_sql(i: &IndexDef, table: &str) -> String {
    format!(
        "CREATE {}INDEX {} ON {} ({})",
        if i.unique { "UNIQUE " } else { "" },
        q(&i.name),
        q(table),
        cols(&i.columns)
    )
}

/// SQL for one operation against the definition as it stands before it.
fn op_sql(
    op: &AlterTable,
    table: &str,
    before: &TableDef,
    after: &TableDef,
) -> Result<Vec<String>, StoreError> {
    let t = q(table);
    let constraint_name =
        |found: Option<&Option<String>>, what: &str| -> Result<String, StoreError> {
            found.cloned().flatten().ok_or_else(|| {
                StoreError::validation(format!("The {what} has no name in the catalog"))
            })
        };
    Ok(match op {
        AlterTable::RenameTable { new_name } => {
            vec![format!("ALTER TABLE {t} RENAME TO {}", q(new_name))]
        }
        AlterTable::RenameColumn { column, new_name } => vec![format!(
            "ALTER TABLE {t} RENAME COLUMN {} TO {}",
            q(column),
            q(new_name)
        )],
        AlterTable::AddColumn { column } => {
            let def = after
                .column(&column.name)
                .cloned()
                .ok_or_else(|| StoreError::validation("column missing"))?;
            let mut sql = format!("ALTER TABLE {t} ADD COLUMN {}", column_sql(&def, false));
            if column.unique {
                sql.push_str(" UNIQUE");
            }
            for c in after.checks.iter().filter(|c| !before.checks.contains(c)) {
                sql.push_str(&format!(
                    " {}CHECK ({})",
                    named(&c.name).trim_end(),
                    c.expression
                ));
            }
            vec![sql]
        }
        AlterTable::DropColumn { column } => {
            vec![format!("ALTER TABLE {t} DROP COLUMN {}", q(column))]
        }
        AlterTable::AlterColumn { column, definition } => {
            let prev = before
                .column(column)
                .cloned()
                .ok_or_else(|| StoreError::validation("column missing"))?;
            let next = after
                .column(column)
                .cloned()
                .ok_or_else(|| StoreError::validation("column missing"))?;
            let c = q(&prev.name);
            let mut out = vec![];
            if prev.logical_type != next.logical_type {
                let ty = pg_type(&next);
                out.push(format!(
                    "ALTER TABLE {t} ALTER COLUMN {c} TYPE {ty} USING {c}::text::{ty}"
                ));
            }
            if prev.nullable != next.nullable {
                out.push(format!(
                    "ALTER TABLE {t} ALTER COLUMN {c} {} NOT NULL",
                    if next.nullable { "DROP" } else { "SET" }
                ));
            }
            if prev.default_expression != next.default_expression {
                out.push(match &next.default_expression {
                    Some(d) => format!("ALTER TABLE {t} ALTER COLUMN {c} SET DEFAULT {d}"),
                    None => format!("ALTER TABLE {t} ALTER COLUMN {c} DROP DEFAULT"),
                });
            }
            let was_unique = before.is_unique_column(&prev.name);
            if definition.unique && !was_unique {
                out.push(format!("ALTER TABLE {t} ADD UNIQUE ({c})"));
            } else if !definition.unique && was_unique {
                let u = before
                    .uniques
                    .iter()
                    .find(|u| u.columns.len() == 1 && u.columns[0] == prev.name);
                out.push(format!(
                    "ALTER TABLE {t} DROP CONSTRAINT {}",
                    q(&constraint_name(u.map(|u| &u.name), "unique constraint")?)
                ));
            }
            // The plan already replaced the column's checks; apply the difference.
            for c in before.checks.iter().filter(|c| !after.checks.contains(c)) {
                // Drop first so a type change is not validated against the old check.
                out.insert(
                    0,
                    format!(
                        "ALTER TABLE {t} DROP CONSTRAINT {}",
                        q(&constraint_name(Some(&c.name), "check constraint")?)
                    ),
                );
            }
            for c in after.checks.iter().filter(|c| !before.checks.contains(c)) {
                out.push(format!(
                    "ALTER TABLE {t} ADD {}CHECK ({})",
                    named(&c.name),
                    c.expression
                ));
            }
            out
        }
        AlterTable::SetPrimaryKey { columns } => {
            let mut out = vec![];
            if let Some(name) = &before.primary_key_name {
                out.push(format!("ALTER TABLE {t} DROP CONSTRAINT {}", q(name)));
            }
            if !columns.is_empty() {
                out.push(format!(
                    "ALTER TABLE {t} ADD PRIMARY KEY ({})",
                    cols(columns)
                ));
            }
            out
        }
        AlterTable::AddForeignKey { .. } => vec![format!(
            "ALTER TABLE {t} ADD {}",
            fk_sql(after.foreign_keys.last().unwrap())
        )],
        AlterTable::DropForeignKey { columns } => {
            let f = before.foreign_keys.iter().find(|f| &f.columns == columns);
            vec![format!(
                "ALTER TABLE {t} DROP CONSTRAINT {}",
                q(&constraint_name(f.map(|f| &f.name), "foreign key")?)
            )]
        }
        AlterTable::AddUnique { columns, name } => vec![format!(
            "ALTER TABLE {t} ADD {}UNIQUE ({})",
            named(name),
            cols(columns)
        )],
        AlterTable::DropUnique { columns } => {
            let u = before.uniques.iter().find(|u| &u.columns == columns);
            vec![format!(
                "ALTER TABLE {t} DROP CONSTRAINT {}",
                q(&constraint_name(u.map(|u| &u.name), "unique constraint")?)
            )]
        }
        AlterTable::AddCheck { expression, name } => {
            let added = after.checks.iter().find(|c| !before.checks.contains(c));
            let name = name.clone().or_else(|| added.and_then(|c| c.name.clone()));
            vec![format!(
                "ALTER TABLE {t} ADD {}CHECK ({expression})",
                named(&name)
            )]
        }
        AlterTable::DropCheck { expression } => {
            let c = before.checks.iter().find(|c| {
                c.expression.trim() == expression.trim()
                    || c.name.as_deref() == Some(expression.as_str())
            });
            vec![format!(
                "ALTER TABLE {t} DROP CONSTRAINT {}",
                q(&constraint_name(c.map(|c| &c.name), "check constraint")?)
            )]
        }
    })
}

impl PostgresRecordStore {
    fn plan(&mut self, table: &str, ops: &[AlterTable]) -> Result<ChangePlan, StoreError> {
        let original = load_def(&mut self.client, &self.schema, table)?;
        let applied = plan::apply_ops(&original, ops, |_, _| (ChangeMode::InPlace, None))
            .map_err(StoreError::validation)?;
        let mut statements = vec![];
        let mut current = original;
        let mut name = table.to_string();
        for op in ops {
            let mut next = plan::apply_ops(&current, std::slice::from_ref(op), |_, _| {
                (ChangeMode::InPlace, None)
            })
            .map_err(StoreError::validation)?;
            name_new_checks(op, &name, &current, &mut next.def);
            statements.extend(op_sql(op, &name, &current, &next.def)?);
            if let AlterTable::RenameTable { new_name } = op {
                name = new_name.clone();
            }
            current = next.def;
        }
        Ok(ChangePlan {
            table: table.into(),
            destructive: applied.operations.iter().any(|o| o.destructive),
            operations: applied.operations,
            rebuild: false,
            statements,
            warnings: applied.warnings,
            impact: None,
        })
    }
    fn run_in_tx(&mut self, statements: &[String]) -> Result<(), StoreError> {
        let mut tx = self.client.transaction().map_err(pe)?;
        for s in statements {
            tx.batch_execute(s).map_err(pe)?;
        }
        tx.commit().map_err(pe)
    }
}
fn numbered(sql: &str) -> String {
    let mut n = 0;
    sql.chars()
        .map(|c| {
            if c == '?' {
                n += 1;
                format!("${n}")
            } else {
                c.to_string()
            }
        })
        .collect()
}

impl RecordStore for PostgresRecordStore {
    fn kind(&self) -> &'static str {
        "postgres"
    }
    fn capabilities(&self) -> StoreCapabilities {
        capabilities::postgres()
    }
    fn table_names(&mut self) -> Result<Vec<String>, StoreError> {
        let rows = self
            .client
            .query("SELECT table_name::text FROM information_schema.tables WHERE table_schema=$1 AND table_type='BASE TABLE' AND table_name NOT LIKE '\\_ixtable\\_%' ORDER BY 1", &[&self.schema])
            .map_err(pe)?;
        Ok(rows.iter().map(|r| r.get(0)).collect())
    }
    fn table_def(&mut self, table: &str) -> Result<TableDef, StoreError> {
        load_def(&mut self.client, &self.schema, table)
    }
    fn insert(&mut self, table: &str, values: &[NamedValue]) -> Result<Vec<DataValue>, StoreError> {
        let mut tx = self.client.transaction().map_err(pe)?;
        let out = insert_on(&mut tx, &self.schema, table, values)?;
        tx.commit().map_err(pe)?;
        Ok(out)
    }
    fn update(
        &mut self,
        table: &str,
        values: &[NamedValue],
        identity: &[DataValue],
        expected: Option<&[NamedValue]>,
    ) -> Result<u64, StoreError> {
        let mut tx = self.client.transaction().map_err(pe)?;
        let out = update_on(&mut tx, &self.schema, table, values, identity, expected)?;
        tx.commit().map_err(pe)?;
        Ok(out)
    }
    fn delete(
        &mut self,
        table: &str,
        identity: &[DataValue],
        expected: Option<&[NamedValue]>,
    ) -> Result<u64, StoreError> {
        let mut tx = self.client.transaction().map_err(pe)?;
        let out = delete_on(&mut tx, &self.schema, table, identity, expected)?;
        tx.commit().map_err(pe)?;
        Ok(out)
    }
    fn execute_batch(&mut self, ops: &[WriteOp]) -> Result<Vec<WriteOutcome>, StoreError> {
        let schema = self.schema.clone();
        let mut tx = self.client.transaction().map_err(pe)?;
        let mut out = vec![];
        for op in ops {
            out.push(apply_op(&mut tx, &schema, op)?);
        }
        tx.commit().map_err(pe)?;
        Ok(out)
    }
    fn create_table(&mut self, spec: &CreateTable) -> Result<Vec<String>, StoreError> {
        let def = plan::def_from_spec(spec).map_err(StoreError::validation)?;
        let statements = create_table_sql(&def);
        self.run_in_tx(&statements)?;
        Ok(statements)
    }
    fn plan_alter(&mut self, table: &str, ops: &[AlterTable]) -> Result<ChangePlan, StoreError> {
        self.plan(table, ops)
    }
    fn alter_table(&mut self, table: &str, ops: &[AlterTable]) -> Result<ChangePlan, StoreError> {
        let plan = self.plan(table, ops)?;
        self.run_in_tx(&plan.statements)?;
        Ok(plan)
    }
    fn drop_table(&mut self, table: &str) -> Result<(), StoreError> {
        load_def(&mut self.client, &self.schema, table)?;
        self.run_in_tx(&[format!("DROP TABLE {}", q(table))])
    }
    fn create_index(&mut self, spec: &CreateIndex) -> Result<(), StoreError> {
        plan::validate_name("Index", &spec.name).map_err(StoreError::validation)?;
        let def = self.table_def(&spec.table)?;
        if spec.columns.is_empty() || spec.columns.iter().any(|c| def.column(c).is_none()) {
            return Err(StoreError::validation("An index needs existing columns"));
        }
        let i = IndexDef {
            name: spec.name.clone(),
            table: spec.table.clone(),
            columns: spec.columns.clone(),
            unique: spec.unique,
            sql: None,
        };
        self.run_in_tx(&[index_sql(&i, &spec.table)])
    }
    fn drop_index(&mut self, name: &str) -> Result<(), StoreError> {
        self.run_in_tx(&[format!("DROP INDEX {}", q(name))])
    }
    fn list_indexes(&mut self, table: Option<&str>) -> Result<Vec<IndexDef>, StoreError> {
        let tables = match table {
            Some(t) => vec![t.to_string()],
            None => self.table_names()?,
        };
        let mut out = vec![];
        for t in tables {
            out.extend(self.table_def(&t)?.indexes);
        }
        Ok(out)
    }
    fn impact(&mut self, table: &str) -> Result<TableImpact, StoreError> {
        let def = self.table_def(table)?;
        let rows: i64 = self
            .client
            .query_one(&format!("SELECT count(*) FROM {}", q(table)), &[])
            .map_err(pe)?
            .get(0);
        let mut inbound = vec![];
        for other in self.table_names()? {
            if other == table {
                continue;
            }
            for f in self
                .table_def(&other)?
                .foreign_keys
                .into_iter()
                .filter(|f| f.target_table == table)
            {
                let wh = f
                    .columns
                    .iter()
                    .map(|x| format!("{} IS NOT NULL", q(x)))
                    .collect::<Vec<_>>()
                    .join(" AND ");
                let refs: i64 = self
                    .client
                    .query_one(
                        &format!("SELECT count(*) FROM {} WHERE {wh}", q(&other)),
                        &[],
                    )
                    .map_err(pe)?
                    .get(0);
                inbound.push(InboundForeignKey {
                    table: other.clone(),
                    columns: f.columns,
                    target_columns: f.target_columns,
                    on_delete: f.on_delete,
                    rows: refs as u64,
                });
            }
        }
        Ok(TableImpact {
            table: table.into(),
            rows: rows as u64,
            inbound_foreign_keys: inbound,
            indexes: def.indexes.iter().map(|i| i.name.clone()).collect(),
            dependents: vec![],
            statements: vec![format!("DROP TABLE {}", q(table))],
        })
    }
    fn run_script(
        &mut self,
        sql: &str,
        record: &[crate::recordstore::Bookkeeping],
        dry_run: bool,
    ) -> Result<ScriptReport, StoreError> {
        if let Some(message) = crate::data::sqltext::transaction_control_error(sql) {
            return Err(crate::recordstore::StoreError::new(
                "VALIDATION_ERROR",
                message,
            ));
        }
        let mut tx = self.client.transaction().map_err(pe)?;
        let mut report = ScriptReport::default();
        tx.batch_execute(sql).map_err(pe)?;
        report.log.push("executed script".into());
        let unvalidated: i64 = tx.query_one("SELECT count(*) FROM pg_constraint c JOIN pg_namespace n ON n.oid = c.connamespace WHERE n.nspname = current_schema() AND NOT c.convalidated", &[]).map_err(pe)?.get(0);
        report
            .health
            .push(format!("unvalidated constraints: {unvalidated}"));
        for (record_sql, binds) in record {
            let params: Vec<&(dyn ToSql + Sync)> =
                binds.iter().map(|b| b as &(dyn ToSql + Sync)).collect();
            tx.execute(&numbered(record_sql), &params).map_err(pe)?;
        }
        if dry_run {
            tx.rollback().map_err(pe)?;
            report.log.push("rolled back (dry run)".into());
        } else {
            tx.commit().map_err(pe)?;
            report.log.push("committed".into());
        }
        Ok(report)
    }
    fn execute_internal(&mut self, sql: &str, binds: &[String]) -> Result<(), StoreError> {
        let params: Vec<&(dyn ToSql + Sync)> =
            binds.iter().map(|b| b as &(dyn ToSql + Sync)).collect();
        if binds.is_empty() {
            self.client.batch_execute(sql).map_err(pe)
        } else {
            self.client
                .execute(&numbered(sql), &params)
                .map(|_| ())
                .map_err(pe)
        }
    }
    fn query_internal(&mut self, sql: &str) -> Result<Vec<Vec<Option<String>>>, StoreError> {
        let rows = self.client.query(sql, &[]).map_err(pe)?;
        Ok(rows
            .iter()
            .map(|r| {
                (0..r.len())
                    .map(|i| match *r.columns()[i].type_() {
                        Type::INT8 => r.get::<_, Option<i64>>(i).map(|v| v.to_string()),
                        Type::INT4 => r.get::<_, Option<i32>>(i).map(|v| v.to_string()),
                        Type::BOOL => r.get::<_, Option<bool>>(i).map(|v| v.to_string()),
                        _ => r.get::<_, Option<String>>(i),
                    })
                    .collect()
            })
            .collect())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::data::{CheckDef, CreateColumn};

    #[test]
    fn check_names_are_deterministic_unique_and_fit_postgres() {
        assert_eq!(check_name("stock", Some("qty"), &[]), "stock_qty_check");
        assert_eq!(
            check_name("stock", Some("qty"), &["stock_qty_check"]),
            "stock_qty_check1"
        );
        assert_eq!(check_name("stock", None, &[]), "stock_check");
        let long = "t".repeat(70);
        let a = check_name(&long, Some("c"), &[]);
        assert!(a.len() <= PG_IDENT_MAX);
        assert_eq!(a, check_name(&long, Some("c"), &[]));
        assert_ne!(a, check_name(&long, Some("d"), &[]));
        let wide = "é".repeat(40);
        assert!(check_name(&wide, Some("c"), &[]).len() <= PG_IDENT_MAX);
    }

    #[test]
    fn a_check_added_by_alter_column_can_be_dropped_in_the_same_batch() {
        let alter = |check: &str| AlterTable::AlterColumn {
            column: "qty".into(),
            definition: CreateColumn {
                name: "qty".into(),
                logical_type: Some(LogicalType::Integer),
                nullable: true,
                check: Some(check.into()),
                ..Default::default()
            },
        };
        let before = TableDef {
            name: "stock".into(),
            columns: vec![ColumnDef {
                name: "qty".into(),
                declared_type: "integer".into(),
                logical_type: LogicalType::Integer,
                nullable: true,
                default_expression: None,
                generated_expression: None,
            }],
            checks: vec![CheckDef {
                name: Some("stock_qty_check".into()),
                expression: "qty > 0".into(),
            }],
            ..Default::default()
        };
        let mut current = before;
        let mut statements = vec![];
        for op in [alter("qty < 100"), alter("qty < 50")] {
            let mut next = plan::apply_ops(&current, std::slice::from_ref(&op), |_, _| {
                (ChangeMode::InPlace, None)
            })
            .unwrap();
            name_new_checks(&op, "stock", &current, &mut next.def);
            statements.extend(op_sql(&op, "stock", &current, &next.def).unwrap());
            current = next.def;
        }
        assert_eq!(
            statements,
            vec![
                r#"ALTER TABLE "stock" DROP CONSTRAINT "stock_qty_check""#,
                r#"ALTER TABLE "stock" ADD CONSTRAINT "stock_qty_check1" CHECK (qty < 100)"#,
                r#"ALTER TABLE "stock" DROP CONSTRAINT "stock_qty_check1""#,
                r#"ALTER TABLE "stock" ADD CONSTRAINT "stock_qty_check" CHECK (qty < 50)"#,
            ]
        );
    }
}
