import { createClient } from "@supabase/supabase-js";

export const E2E_USER_EMAIL = "e2e@example.com";
export const E2E_USER_PASSWORD = "e2e-test-password";

export const SUPABASE_URL = process.env.SUPABASE_URL ?? "http://127.0.0.1:54321";
// Well-known local Supabase service_role key generated by `supabase init`.
// Only ever valid against a local dev stack; override via env for CI.
export const SUPABASE_SERVICE_ROLE_KEY =
  process.env.SUPABASE_SERVICE_ROLE_KEY ??
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU";

async function isSupabaseUp(): Promise<boolean> {
  try {
    const response = await fetch(`${SUPABASE_URL}/auth/v1/health`, {
      signal: AbortSignal.timeout(3000),
    });
    return response.ok;
  } catch {
    return false;
  }
}

/**
 * Probes the local Supabase stack and, if it's up, seeds a deterministic e2e
 * user via the admin API. Sets E2E_SUPABASE_AVAILABLE so auth specs can skip
 * themselves when Supabase isn't running (e.g. no Docker available).
 */
export default async function globalSetup(): Promise<void> {
  const up = await isSupabaseUp();
  process.env.E2E_SUPABASE_AVAILABLE = up ? "true" : "false";

  if (!up) {
    console.warn(
      `[global-setup] Supabase is not reachable at ${SUPABASE_URL}. Auth specs will be skipped. Run \`supabase start\` to enable them.`,
    );
    return;
  }

  const admin = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
    auth: { autoRefreshToken: false, persistSession: false },
  });

  const { data: existing } = await admin.auth.admin.listUsers();
  const existingUser = existing?.users.find((user) => user.email === E2E_USER_EMAIL);

  if (existingUser) {
    await admin.auth.admin.updateUserById(existingUser.id, {
      password: E2E_USER_PASSWORD,
      email_confirm: true,
    });
  } else {
    await admin.auth.admin.createUser({
      email: E2E_USER_EMAIL,
      password: E2E_USER_PASSWORD,
      email_confirm: true,
    });
  }
}
