#!/usr/bin/env node
// Generates the "Contract" appendix of docs/decisions/cloud-architecture.md
// from the Edge Functions themselves: the request/response lines of each
// function's header comment, the error codes it can return (thrown directly
// or by the shared helpers it calls), its RATE_LIMITS entry, and the
// top-level reply keys recorded from the local stack
// (web/e2e/service-qa/fixtures/contract, see specs/contract.spec.ts).
//
//   node scripts/cloud/contract-doc.mjs          rewrite the appendix
//   node scripts/cloud/contract-doc.mjs --check  exit 1 when it is stale
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const functionsDir = join(root, "supabase", "functions");
const fixturesDir = join(root, "web", "e2e", "service-qa", "fixtures", "contract");
export const DOC = join(root, "docs", "decisions", "cloud-architecture.md");
const START = "<!-- contract:start (generated by scripts/cloud/contract-doc.mjs) -->";
const END = "<!-- contract:end -->";

// Codes the shared helpers return (supabase/functions/_shared).
const HELPER_CODES = {
  requireUser: ["UNAUTHENTICATED"],
  readJson: ["VALIDATION"],
  enforceNamedRateLimit: ["RATE_LIMITED"],
  loadApp: ["NOT_FOUND"],
  requireAppOwner: ["FORBIDDEN"],
  requireAppAdmin: ["FORBIDDEN"],
  requireRuntimeAccess: ["FORBIDDEN", "REVOKED"],
  requireEntitlement: ["ENTITLEMENT_REQUIRED"],
  requireBillingApp: ["NOT_FOUND", "FORBIDDEN"],
  readPublishInput: ["VALIDATION"],
  preparePublish: ["VALIDATION", "NOT_FOUND", "TOO_LARGE"],
  rpc: ["VERSION_CONFLICT", "ENTITLEMENT_REQUIRED", "NOT_FOUND", "FORBIDDEN", "VALIDATION"],
  requireEmailConfirmations: ["INTERNAL"],
  exchangeLimitSubjects: ["INTERNAL"],
};
const ORDER = [
  "UNAUTHENTICATED",
  "FORBIDDEN",
  "REVOKED",
  "NOT_FOUND",
  "VERSION_CONFLICT",
  "TOO_LARGE",
  "ENTITLEMENT_REQUIRED",
  "VALIDATION",
  "PENDING",
  "RATE_LIMITED",
  "METHOD_NOT_ALLOWED",
  "INTERNAL",
];

function rateLimits() {
  const source = readFileSync(join(functionsDir, "_shared", "rateLimit.ts"), "utf8");
  const out = {};
  for (const m of source.matchAll(/"([a-z-]+)": \{ max: (\d+), windowSeconds: (\d+) \}/g)) {
    const seconds = Number(m[3]);
    const window = seconds % 3600 === 0 ? `${seconds / 3600} h` : `${seconds / 60} min`;
    out[m[1]] = `${m[2]} / ${window}`;
  }
  return out;
}

function header(source) {
  const lines = [];
  for (const line of source.split("\n")) {
    if (!line.startsWith("//")) break;
    lines.push(line.replace(/^\/\/ ?/, ""));
  }
  return lines;
}

/** The request → reply lines of a header comment (`POST {…} → {…}` or `name {…} → {…}`). */
function signature(name, lines) {
  const blocks = [];
  let block = null;
  for (const line of lines) {
    const text = line.trim();
    if (/^(POST|GET)\b/.test(text) || text.startsWith(`${name} {`)) {
      block = [text];
      blocks.push(block);
    } else if (block && /^\s{2,}\S/.test(line)) block.push(text);
    else block = null;
  }
  return blocks
    .map((b) => b.join(" "))
    .join("; ")
    .replace(/\s+/g, " ")
    .replace(/\|/g, "\\|");
}

function errors(source) {
  const codes = new Set();
  for (const m of source.matchAll(/HttpError\(\s*"([A-Z_]+)"/g)) codes.add(m[1]);
  for (const [helper, list] of Object.entries(HELPER_CODES))
    if (new RegExp(`\\b${helper}\\(`).test(source)) for (const code of list) codes.add(code);
  return ORDER.filter((code) => codes.has(code));
}

function recordedKeys() {
  const out = {};
  if (!existsSync(fixturesDir)) return out;
  for (const file of readdirSync(fixturesDir)
    .filter((f) => f.endsWith(".json"))
    .sort()) {
    const fixture = JSON.parse(readFileSync(join(fixturesDir, file), "utf8"));
    if (fixture.status !== 200 || !fixture.response || typeof fixture.response !== "object")
      continue;
    const keys = (out[fixture.function] ??= new Set());
    for (const key of Object.keys(fixture.response)) keys.add(key);
  }
  return out;
}

export function renderContract() {
  const limits = rateLimits();
  const recorded = recordedKeys();
  const rows = readdirSync(functionsDir, { withFileTypes: true })
    .filter((e) => e.isDirectory() && existsSync(join(functionsDir, e.name, "index.ts")))
    .map((e) => e.name)
    .sort()
    .map((name) => {
      const source = readFileSync(join(functionsDir, name, "index.ts"), "utf8");
      const keys = recorded[name] ? [...recorded[name]].map((k) => `\`${k}\``).join(", ") : "";
      return `| \`${name}\` | ${signature(name, header(source)) || "see the function header"} | ${errors(source).join(", ")} | ${limits[name] ?? "none"} | ${keys} |`;
    });
  return [
    START,
    "",
    "| Function | Request → reply (from the function's header) | Error codes (direct and via shared helpers) | Rate limit | Recorded reply keys |",
    "|---|---|---|---|---|",
    ...rows,
    "",
    END,
  ].join("\n");
}

export function updatedDoc(text = readFileSync(DOC, "utf8")) {
  const start = text.indexOf(START);
  const end = text.indexOf(END);
  if (start < 0 || end < 0) throw new Error(`${DOC} has no contract markers`);
  return text.slice(0, start) + renderContract() + text.slice(end + END.length);
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const current = readFileSync(DOC, "utf8");
  const next = updatedDoc(current);
  if (process.argv.includes("--check")) {
    if (next !== current) {
      console.error("The Contract appendix is stale: run node scripts/cloud/contract-doc.mjs");
      process.exit(1);
    }
  } else {
    writeFileSync(DOC, next);
    console.log(`updated ${DOC}`);
  }
}
