#!/usr/bin/env node
// Generates local-only Edge Function secrets in supabase/functions/.env.local
// (gitignored). Never use these values outside a local stack.
//
//   node scripts/cloud/dev-secrets.mjs          # keep an existing file
//   node scripts/cloud/dev-secrets.mjs --force  # rotate everything
//
// Prints the cloud public key so the desktop/test side can pin it via
// IXTABLE_CLOUD_PUBLIC_KEY (SPKI DER base64; the raw 32-byte key is in
// IXTABLE_CLOUD_PUBLIC_KEY_RAW).
import { generateKeyPairSync, randomBytes } from "node:crypto";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
export const ENV_FILE = join(root, "supabase", "functions", ".env.local");
// `supabase start` loads supabase/functions/.env into the Edge runtime, so the
// same values are mirrored there (also gitignored).
export const START_ENV_FILE = join(root, "supabase", "functions", ".env");

export function parseEnv(text) {
  const out = {};
  for (const line of text.split(/\r?\n/)) {
    const match = /^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/.exec(line);
    if (match) out[match[1]] = match[2].replace(/^"(.*)"$/, "$1");
  }
  return out;
}

export function readDevSecrets() {
  return existsSync(ENV_FILE) ? parseEnv(readFileSync(ENV_FILE, "utf8")) : {};
}

export function generateDevSecrets() {
  const { privateKey, publicKey } = generateKeyPairSync("ed25519");
  const spki = publicKey.export({ format: "der", type: "spki" });
  return {
    IXTABLE_CLOUD_SIGNING_KEY: privateKey
      .export({ format: "der", type: "pkcs8" })
      .toString("base64"),
    IXTABLE_CLOUD_PUBLIC_KEY: spki.toString("base64"),
    IXTABLE_CLOUD_PUBLIC_KEY_RAW: spki.subarray(spki.length - 32).toString("base64"),
    IXTABLE_KEK_V1: randomBytes(32).toString("base64"),
    IXTABLE_KEK_CURRENT_VERSION: "1",
    IXTABLE_FINGERPRINT_SECRET: randomBytes(32).toString("base64"),
    STRIPE_WEBHOOK_SECRET: `whsec_test_${randomBytes(24).toString("hex")}`,
    BILLING_PROVIDER: "fake",
    SITE_URL: "http://127.0.0.1:3001",
    IXTABLE_CLOUD_VERSION: "0.1.0-local",
  };
}

export function ensureDevSecrets({ force = false } = {}) {
  const existing = readDevSecrets();
  if (!force && existing.IXTABLE_CLOUD_SIGNING_KEY && existing.IXTABLE_KEK_V1) {
    writeFileSync(START_ENV_FILE, readFileSync(ENV_FILE, "utf8"), { mode: 0o600 });
    return { secrets: existing, created: false };
  }
  const secrets = generateDevSecrets();
  const body = [
    "# Local-only ixtable Cloud secrets. Generated by scripts/cloud/dev-secrets.mjs.",
    "# Gitignored. Never reuse these values outside a local Supabase stack.",
    ...Object.entries(secrets).map(([key, value]) => `${key}=${value}`),
    "",
  ].join("\n");
  writeFileSync(ENV_FILE, body, { mode: 0o600 });
  writeFileSync(START_ENV_FILE, body, { mode: 0o600 });
  return { secrets, created: true };
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const { secrets, created } = ensureDevSecrets({ force: process.argv.includes("--force") });
  console.log(`${created ? "Wrote" : "Kept"} ${ENV_FILE}`);
  console.log(`IXTABLE_CLOUD_PUBLIC_KEY=${secrets.IXTABLE_CLOUD_PUBLIC_KEY}`);
}
