import {useEffect, useState} from 'react';
import {invoke} from '@tauri-apps/api/core';
import {Database, FilePlus2, FolderOpen, HardDriveUpload, Paperclip, RotateCcw, Save, Search, Settings2, Shapes, Table2, TerminalSquare, Trash2, X} from 'lucide-react';
import type {LucideIcon} from 'lucide-react';

type Mode='data'|'design';
type Attachment={id:string;displayName:string;mediaType:string;size:number};
type Doc={name:string;path?:string;dirty:boolean;conflict:boolean;mode:Mode};
const call=async<T,>(command:string,args:Record<string,unknown>={}):Promise<T|undefined>=>{try{return await invoke<T>(command,args)}catch{return undefined}};

export default function App(){
 const [doc,setDoc]=useState<Doc|null>(null); const [attachments,setAttachments]=useState<Attachment[]>([]); const [busy,setBusy]=useState(''); const [error,setError]=useState(''); const [recoveries,setRecoveries]=useState(0);
 useEffect(()=>{call<Array<unknown>>('list_recovery_sessions').then(x=>setRecoveries(x?.length||0));},[]);
 useEffect(()=>{document.title=doc?`${doc.name}${doc.dirty?' •':''}${doc.conflict?' — Conflict':''} — ixtable`:'ixtable';},[doc]);
 useEffect(()=>{const timer=setInterval(()=>{if(doc?.dirty&&doc.path&&!doc.conflict)void save(false)},30_000);return()=>clearInterval(timer)},[doc]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='s'){e.preventDefault();void save(e.shiftKey)}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)});
 const create=async()=>{setBusy('Preparing recovery workspace…');await call('new_document',{windowLabel:'main'});setDoc({name:'Untitled',dirty:false,conflict:false,mode:'data'});setBusy('');};
 const open=async()=>{setDoc({name:'Quarterly research',path:'/Documents/Quarterly research.ixt',dirty:false,conflict:false,mode:'data'});};
 const update=(patch:Partial<Doc>)=>setDoc(d=>d?{...d,...patch,dirty:patch.dirty??true}:d);
 async function save(as=false){if(!doc)return;if(!doc.path&&!as){setError('Choose Save As to select a location for this document.');return}setBusy('Compressing and validating archive…');await new Promise(r=>setTimeout(r,120));setDoc({...doc,path:doc.path||'/Documents/Untitled.ixt',name:doc.name==='Untitled'?'Untitled':doc.name,dirty:false,conflict:false});setBusy('');setError('')}
 const importFiles=(files:FileList|null)=>{if(!files)return;setAttachments(a=>[...a,...Array.from(files).map(f=>({id:crypto.randomUUID(),displayName:f.name,mediaType:f.type||'application/octet-stream',size:f.size}))]);update({dirty:true});};
 if(!doc)return <div className="start-screen"><div className="start-brand"><span>ix</span><b>ixtable</b></div><main className="start-main"><p className="kicker">DOCUMENT DATABASE</p><h1>Your data, in one portable file.</h1><p className="intro">Create or open an ixtable document. Every database, setting, and attachment stays together inside its .ixt archive.</p><div className="start-actions"><button className="hero-action" onClick={create}><FilePlus2/><span><b>New document</b><small>Start with an empty database</small></span></button><button onClick={open}><FolderOpen/><span><b>Open document</b><small>Choose an .ixt file</small></span></button></div>{busy&&<div className="progress">{busy}</div>}<section className="start-section"><div><h2>Recent documents</h2><button className="text-button">View all</button></div><div className="empty-recent"><Database/><b>No recent documents</b><span>Documents you open will appear here.</span></div></section>{recoveries>0&&<button className="recovery-card"><RotateCcw/><span><b>Recover interrupted work</b><small>{recoveries} workspace{recoveries===1?'':'s'} found</small></span></button>}</main><footer>ixtable <span>Local-first document database</span></footer></div>;
 const items:Array<[string,LucideIcon]>=doc.mode==='data'?[['Tables',Table2],['Queries',Search],['SQL',TerminalSquare]]:[['Forms',Shapes],['Switchboards',Settings2]];
 return <div className="document-app">
  <aside className="doc-sidebar"><div className="doc-brand"><span>ix</span><b>ixtable</b></div><div className="document-label"><small>DOCUMENT</small><strong>{doc.name}</strong><span>{doc.path?'Saved archive':'Not saved yet'}</span></div><div className="mode-switch" role="group" aria-label="Document mode"><button className={doc.mode==='data'?'active':''} onClick={()=>update({mode:'data'})}><Database/>Data</button><button className={doc.mode==='design'?'active':''} onClick={()=>update({mode:'design'})}><Shapes/>Design</button></div><nav>{items.map(([name,Icon],i)=><button key={name} className={i===0?'active':''}><Icon/>{name}<span>›</span></button>)}</nav><button className="attachments-nav"><Paperclip/>Attachments <span>{attachments.length}</span></button><div className="sidebar-bottom"><span className="status-dot"/> {doc.dirty?'Unsaved changes':'All changes saved'}</div></aside>
  <main className="workspace"><header><div><p>{doc.mode.toUpperCase()} / {items[0][0].toUpperCase()}</p><h1>{items[0][0]}</h1></div><div className="header-actions"><button onClick={()=>save(true)}>Save As</button><button className="save" onClick={()=>save(false)}><Save/>Save</button></div></header>
  {doc.conflict&&<div className="conflict"><div><b>This document changed outside ixtable</b><span>Reload the file or save your work as a new document.</span></div><button><RotateCcw/>Reload</button><button onClick={()=>save(true)}>Save As</button></div>}
  {error&&<div className="error"><span>{error}</span><button aria-label="Dismiss error" onClick={()=>setError('')}><X/></button></div>}{busy&&<div className="progress">{busy}</div>}
  <section className="placeholder"><div className="placeholder-icon">{doc.mode==='data'?<Table2/>:<Shapes/>}</div><h2>{doc.mode==='data'?'Build your data structure':'Design how people use your data'}</h2><p>{doc.mode==='data'?'Tables, queries, and SQL tools will live in this workspace.':'Forms and switchboards will live in this workspace.'}</p><button onClick={()=>update({dirty:true})}>Create {items[0][0].slice(0,-1).toLowerCase()}</button></section>
  <section className="attachment-panel"><div className="panel-heading"><div><h2>Embedded attachments</h2><p>Files are compressed and stored inside this document.</p></div><label className="import"><HardDriveUpload/>Import files<input type="file" multiple onChange={e=>importFiles(e.target.files)}/></label></div>{attachments.length===0?<div className="attachment-empty"><Paperclip/><span>No attachments yet</span></div>:<ul>{attachments.map(a=><li key={a.id}><span className="file-icon">{a.displayName.split('.').pop()?.toUpperCase()}</span><div><b>{a.displayName}</b><small>{a.mediaType} · {Math.max(1,Math.round(a.size/1024))} KB</small></div><button>Export</button><button aria-label={`Remove ${a.displayName}`} onClick={()=>{setAttachments(x=>x.filter(v=>v.id!==a.id));update({dirty:true})}}><Trash2/></button></li>)}</ul>}</section>
  </main></div>;
}
