import { themes as prismThemes } from "prism-react-renderer";
import type { Config } from "@docusaurus/types";
import type * as Preset from "@docusaurus/preset-classic";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const SUPABASE_URL = process.env.SUPABASE_URL ?? "http://127.0.0.1:54321";
// This is the well-known local Supabase anon key generated by `supabase init`.
// It is safe to ship in client bundles; it has no access without RLS grants.
const SUPABASE_ANON_KEY =
  process.env.SUPABASE_ANON_KEY ??
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0";

const config: Config = {
  title: "ixtable",
  tagline: "Build the business app you need",
  favicon: "img/favicon.svg",

  future: {
    v4: true,
    faster: true,
  },

  url: "https://ixtable.pages.dev",
  baseUrl: "/",

  organizationName: "ixtable",
  projectName: "ixtable",

  onBrokenLinks: "throw",

  i18n: {
    defaultLocale: "en",
    locales: ["en"],
  },

  customFields: {
    supabaseUrl: SUPABASE_URL,
    supabaseAnonKey: SUPABASE_ANON_KEY,
    // OAuth buttons stay visible but disabled until the provider is configured
    // in Supabase (supabase/config.toml [auth.external.*] locally, the hosted
    // project in production). OAUTH_ENABLED turns on every provider at once.
    oauthEnabled: process.env.OAUTH_ENABLED === "true",
    googleAuthEnabled: process.env.OAUTH_GOOGLE_ENABLED === "true",
    microsoftAuthEnabled: process.env.OAUTH_MICROSOFT_ENABLED === "true",
  },

  presets: [
    [
      "classic",
      {
        docs: {
          sidebarPath: "./sidebars.ts",
        },
        blog: false,
        theme: {
          customCss: "./src/css/custom.css",
        },
      } satisfies Preset.Options,
    ],
  ],

  themeConfig: {
    image: "img/social-card.png",
    colorMode: {
      respectPrefersColorScheme: true,
    },
    navbar: {
      title: "ixtable",
      logo: {
        alt: "ixtable",
        src: "img/logo.svg",
        srcDark: "img/logo-dark.svg",
        width: 28,
        height: 28,
      },
      items: [
        {
          type: "docSidebar",
          sidebarId: "docsSidebar",
          position: "left",
          label: "Docs",
        },
        { to: "/pricing", label: "Pricing", position: "left" },
        { to: "/cloud", label: "Cloud", position: "left" },
        {
          href: "https://github.com/ixtable/ixtable",
          label: "GitHub",
          position: "right",
        },
        {
          type: "custom-authNavbarItem",
          position: "right",
        },
      ],
    },
    footer: {
      style: "dark",
      links: [
        {
          title: "Docs",
          items: [
            {
              label: "Overview",
              to: "/docs/",
            },
            {
              label: "Getting started with Cloud",
              to: "/docs/cloud/getting-started",
            },
            {
              label: "Security",
              to: "/docs/cloud/security",
            },
          ],
        },
        {
          title: "Legal",
          items: [
            { label: "Privacy policy", to: "/docs/legal/privacy" },
            { label: "Terms of service", to: "/docs/legal/terms" },
          ],
        },
        {
          title: "More",
          items: [
            { label: "Pricing", to: "/pricing" },
            {
              label: "GitHub",
              href: "https://github.com/ixtable/ixtable",
            },
          ],
        },
      ],
      copyright: `Copyright © ${new Date().getFullYear()} ixtable.`,
    },
    prism: {
      theme: prismThemes.github,
      darkTheme: prismThemes.dracula,
    },
  } satisfies Preset.ThemeConfig,

  plugins: [
    function chunkSplitPlugin() {
      return {
        name: "chunk-split-plugin",
        configureWebpack(_config: unknown, isServer: boolean) {
          if (isServer) {
            return {};
          }
          return {
            optimization: {
              splitChunks: {
                cacheGroups: {
                  supabase: {
                    test: /[\\/]node_modules[\\/]@supabase[\\/]/,
                    name: "chunk-supabase",
                    chunks: "all",
                  },
                },
              },
            },
          };
        },
      };
    },
  ],
};

export default config;
