import { themes as prismThemes } from "prism-react-renderer";
import type { Config } from "@docusaurus/types";
import type * as Preset from "@docusaurus/preset-classic";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const SUPABASE_URL = process.env.SUPABASE_URL ?? "http://127.0.0.1:54321";
// This is the well-known local Supabase anon key generated by `supabase init`.
// It is safe to ship in client bundles; it has no access without RLS grants.
const SUPABASE_ANON_KEY =
  process.env.SUPABASE_ANON_KEY ??
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0";

// GA4 runs on the marketing site only, and only when the deploy workflow sets
// GA4_MEASUREMENT_ID. Local builds and e2e runs ship no tracking. The desktop
// app and ixtable Cloud never load third-party analytics.
const GA4_MEASUREMENT_ID = process.env.GA4_MEASUREMENT_ID?.trim();

const config: Config = {
  title: "ixtable",
  tagline: "Build the business app you need",
  favicon: "img/favicon.svg",

  future: {
    v4: true,
    faster: true,
  },

  url: "https://ixtable.com",
  baseUrl: "/",
  // Cloudflare Pages serves each page from `<path>/index.html` and answers
  // `/<path>` with a 308 to `/<path>/`. Emit trailing-slash URLs so canonical
  // links and the sitemap point at the final URL, not at a redirect.
  trailingSlash: true,

  organizationName: "ixtable",
  projectName: "ixtable",

  onBrokenLinks: "throw",

  i18n: {
    defaultLocale: "en",
    locales: ["en"],
  },

  customFields: {
    supabaseUrl: SUPABASE_URL,
    supabaseAnonKey: SUPABASE_ANON_KEY,
    // Flip to true once real OAuth provider credentials are configured in
    // supabase/config.toml (see the [auth.external.*] sections).
    oauthEnabled: process.env.OAUTH_ENABLED === "true",
  },

  presets: [
    [
      "classic",
      {
        docs: {
          sidebarPath: "./sidebars.ts",
        },
        blog: {
          path: "blog",
          blogTitle: "Product notes and updates",
          blogDescription:
            "Notes on building ixtable, the free local-first desktop app builder, and ixtable Cloud for private app distribution.",
          showReadingTime: true,
          blogSidebarCount: "ALL",
          blogSidebarTitle: "All posts",
          onUntruncatedBlogPosts: "ignore",
        },
        ...(GA4_MEASUREMENT_ID
          ? { gtag: { trackingID: GA4_MEASUREMENT_ID, anonymizeIP: true } }
          : {}),
        sitemap: {
          ignorePatterns: ["/login/**", "/account/**", "/forgot-password/**", "/reset-password/**"],
        },
        theme: {
          customCss: "./src/css/custom.css",
        },
      } satisfies Preset.Options,
    ],
  ],

  themeConfig: {
    image: "img/social-card.svg",
    colorMode: {
      respectPrefersColorScheme: true,
    },
    navbar: {
      title: "ixtable",
      logo: {
        alt: "ixtable logo",
        src: "img/favicon.svg",
      },
      items: [
        {
          type: "docSidebar",
          sidebarId: "tutorialSidebar",
          position: "left",
          label: "Docs",
        },
        { to: "/pricing", label: "Pricing", position: "left" },
        { to: "/blog", label: "Blog", position: "left" },
        {
          href: "https://github.com/ixtable/ixtable",
          label: "GitHub",
          position: "right",
        },
        {
          type: "custom-authNavbarItem",
          position: "right",
        },
      ],
    },
    footer: {
      style: "dark",
      links: [
        {
          title: "Docs",
          items: [
            {
              label: "Overview",
              to: "/docs/",
            },
          ],
        },
        {
          title: "Product",
          items: [
            { label: "Pricing", to: "/pricing" },
            { label: "Blog", to: "/blog" },
          ],
        },
        {
          title: "More",
          items: [
            {
              label: "GitHub",
              href: "https://github.com/ixtable/ixtable",
            },
          ],
        },
      ],
      copyright: `Copyright © ${new Date().getFullYear()} ixtable.`,
    },
    prism: {
      theme: prismThemes.github,
      darkTheme: prismThemes.dracula,
    },
  } satisfies Preset.ThemeConfig,

  plugins: [
    function chunkSplitPlugin() {
      return {
        name: "chunk-split-plugin",
        configureWebpack(_config: unknown, isServer: boolean) {
          if (isServer) {
            return {};
          }
          return {
            optimization: {
              splitChunks: {
                cacheGroups: {
                  supabase: {
                    test: /[\\/]node_modules[\\/]@supabase[\\/]/,
                    name: "chunk-supabase",
                    chunks: "all",
                  },
                },
              },
            },
          };
        },
      };
    },
  ],
};

export default config;
